import lightMapPreview from "../assets/images/lightMapPreview.png";
import darkMapPreview from "../assets/images/darkMapPreview.png";
import streetsMapPreview from "../assets/images/streetsMapPreview.png";
import satelliteMapPreview from "../assets/images/satelliteMapPreview.png";

export const INITIAL_VIEW = {
  LONGITUDE: 6.143724445834019,
  LATITUDE: 46.203988837044086,
  ZOOM: 10.5,
};

export const MAP_STYLES = [
  {
    TITLE: "Light",
    URL: "mapbox://styles/lamapch/clwoz41jt011101r0bzo85ivl",
    IMAGE: lightMapPreview,
  },
  {
    TITLE: "Dark",
    URL: "mapbox://styles/lamapch/clwrfixmy013601pnfpzzhfpr",
    IMAGE: darkMapPreview,
  },
  {
    TITLE: "Streets",
    URL: "mapbox://styles/lamapch/clwrp200h00kl01po0jjj6hai",
    IMAGE: streetsMapPreview,
  },
  {
    TITLE: "Satellite",
    URL: "mapbox://styles/lamapch/clwrojbwp017a01r0b3xj521f",
    IMAGE: satelliteMapPreview,
  },
];

export const FILTERS_OPTIONS = {
  CANTON: [{ value: "geneve", label: "Geneve" }],
  POST_CODE: Array.from({ length: 1298 - 1201 + 1 }, (_, i) => 1201 + i).map(
    (code) => ({ value: code, label: code })
  ),
  LOCALITY: [
    { value: "Aire-la-Ville", label: "Aire-la-Ville" },
    { value: "Anières", label: "Anières" },
    { value: "Athenaz (Avusy)", label: "Athenaz (Avusy)" },
    { value: "Avully", label: "Avully" },
    { value: "Aïre", label: "Aïre" },
    { value: "Bellevue", label: "Bellevue" },
    { value: "Bernex", label: "Bernex" },
    { value: "Carouge GE", label: "Carouge GE" },
    { value: "Cartigny", label: "Cartigny" },
    { value: "Chambésy", label: "Chambésy" },
    { value: "Chancy", label: "Chancy" },
    { value: "Choulex", label: "Choulex" },
    { value: "Châtelaine", label: "Châtelaine" },
    { value: "Chêne-Bougeries", label: "Chêne-Bougeries" },
    { value: "Chêne-Bourg", label: "Chêne-Bourg" },
    { value: "Cointrin", label: "Cointrin" },
    { value: "Collex", label: "Collex" },
    { value: "Collonge-Bellerive", label: "Collonge-Bellerive" },
    { value: "Cologny", label: "Cologny" },
    { value: "Conches", label: "Conches" },
    { value: "Confignon", label: "Confignon" },
    { value: "Corsier GE", label: "Corsier GE" },
    { value: "Céligny", label: "Céligny" },
    { value: "Dardagny", label: "Dardagny" },
    { value: "Genthod", label: "Genthod" },
    { value: "Genève", label: "Genève" },
    { value: "Grand-Lancy", label: "Grand-Lancy" },
    { value: "Gy", label: "Gy" },
    { value: "Hermance", label: "Hermance" },
    { value: "Jussy", label: "Jussy" },
    { value: "La Croix-de-Rozon", label: "La Croix-de-Rozon" },
    { value: "La Plaine", label: "La Plaine" },
    { value: "Laconnex", label: "Laconnex" },
    { value: "Le Grand-Saconnex", label: "Le Grand-Saconnex" },
    { value: "Le Lignon", label: "Le Lignon" },
    { value: " Les Acacias", label: " Les Acacias" },
    { value: "Les Avanchets", label: "Les Avanchets" },
    { value: "Meinier", label: "Meinier" },
    { value: "Meyrin", label: "Meyrin" },
    { value: "Onex", label: "Onex" },
    { value: "Perly", label: "Perly" },
    { value: "Petit-Lancy", label: "Petit-Lancy" },
    { value: "Plan-les-Ouates", label: "Plan-les-Ouates" },
    { value: "Presinge", label: "Presinge" },
    { value: "Puplinge", label: "Puplinge" },
    { value: "Russin", label: "Russin" },
    { value: "Satigny", label: "Satigny" },
    { value: "Soral", label: "Soral" },
    { value: "Thônex", label: "Thônex" },
    { value: "Troinex", label: "Troinex" },
    { value: "Vandoeuvres", label: "Vandoeuvres" },
    { value: "Vernier", label: "Vernier" },
    { value: "Versoix", label: "Versoix" },
    { value: "Vessy", label: "Vessy" },
    { value: "Veyrier", label: "Veyrier" },
    { value: "Vésenaz", label: "Vésenaz" },
  ],
  FILE_STATUS: [
    { value: "ACCEPTE", label: "ACCEPTE" },
    { value: "CHANTIER", label: "CHANTIER" },
    { value: "REFUSE", label: "REFUSE" },
    { value: "ORMIG", label: "ORMIG" },
    { value: "RENVOYE", label: "RENVOYE" },
    { value: "REFUS ENTREE", label: "REFUS ENTREE" },
    { value: "DECIDE", label: "DECIDE" },
    { value: "CADUQUE", label: "CADUQUE" },
    { value: "EDISCAN", label: "EDISCAN" },
    { value: "TERMINE", label: "TERMINE" },
    { value: "ENREGISTRE", label: "ENREGISTRE" },
    { value: "NON ASSUJETTI", label: "NON ASSUJETTI" },
    { value: "INSTRUCTION", label: "INSTRUCTION" },
    { value: "PROCEDURE AMS", label: "PROCEDURE AMS" },
    { value: "ENREGISTREMENT", label: "ENREGISTREMENT" },
    { value: "VA", label: "VA" },
    { value: "RECOURS", label: "RECOURS" },
    { value: "ARCHANT", label: "ARCHANT" },
    { value: "CLOTURE ADMIN", label: "CLOTURE ADMIN" },
    { value: "AUTORISATION ANNULEE", label: "AUTORISATION ANNULEE" },
    { value: "ARCHIVE", label: "ARCHIVE" },
    { value: "INSTRUCTION DA", label: "INSTRUCTION DA" },
    { value: "EN SUSPENS", label: "EN SUSPENS" },
    { value: "ABANDONNE", label: "ABANDONNE" },
    { value: "ADOPTE", label: "ADOPTE" },
  ],
  COMMUNE: [
    { value: "Aire-la-Ville", label: "Aire-la-Ville" },
    { value: "Anières", label: "Anières" },
    { value: "Avully", label: "Avully" },
    { value: "Avusy", label: "Avusy" },
    { value: "Bardonnex", label: "Bardonnex" },
    { value: "Bellevue", label: "Bellevue" },
    { value: "Bernex", label: "Bernex" },
    { value: "Carouge", label: "Carouge" },
    { value: "Cartigny", label: "Cartigny" },
    { value: "Chancy", label: "Chancy" },
    { value: "Choulex", label: "Choulex" },
    { value: "Chêne-Bougeries", label: "Chêne-Bougeries" },
    { value: "Chêne-Bourg", label: "Chêne-Bourg" },
    { value: "Collex-Bossy", label: "Collex-Bossy" },
    { value: "Collonge-Bellerive", label: "Collonge-Bellerive" },
    { value: "Cologny", label: "Cologny" },
    { value: "Confignon", label: "Confignon" },
    { value: "Corsier", label: "Corsier" },
    { value: "Céligny", label: "Céligny" },
    { value: "Dardagny", label: "Dardagny" },
    { value: "Genthod", label: "Genthod" },
    { value: "Genève-Cité", label: "Genève-Cité" },
    { value: "Genève-Eaux-Vives", label: "Genève-Eaux-Vives" },
    { value: "Genève-Petit-Saconnex", label: "Genève-Petit-Saconnex" },
    { value: "Genève-Plainpalais", label: "Genève-Plainpalais" },
    { value: "Grand-Saconnex", label: "Grand-Saconnex" },
    { value: "Gy", label: "Gy" },
    { value: "Hermance", label: "Hermance" },
    { value: "Jussy", label: "Jussy" },
    { value: "Laconnex", label: "Laconnex" },
    { value: "Lancy", label: "Lancy" },
    { value: "Meinier", label: "Meinier" },
    { value: "Meyrin", label: "Meyrin" },
    { value: "Onex", label: "Onex" },
    { value: "Perly-Certoux", label: "Perly-Certoux" },
    { value: "Plan-les-Ouates", label: "Plan-les-Ouates" },
    { value: "Pregny-Chambésy", label: "Pregny-Chambésy" },
    { value: "Presinge", label: "Presinge" },
    { value: "Puplinge", label: "Puplinge" },
    { value: "Russin", label: "Russin" },
    { value: "Satigny", label: "Satigny" },
    { value: "Soral", label: "Soral" },
    { value: "Thônex", label: "Thônex" },
    { value: "Troinex", label: "Troinex" },
    { value: "Vandoeuvres", label: "Vandoeuvres" },
    { value: "Vernier", label: "Vernier" },
    { value: "Versoix", label: "Versoix" },
    { value: "Veyrier", label: "Veyrier" },
  ],
  TRANSACTION_TYPE: [
    { value: "Achat", label: "Achat" },
    { value: "Achat Donation", label: "Achat Donation" },
    { value: "Achat - Donation", label: "Achat - Donation" },
    {
      value: "Acquisition de bien sans maître",
      label: "Acquisition de bien sans maître",
    },
    { value: "Adjudication", label: "Adjudication" },
    { value: "Apport", label: "Apport" },
    { value: "Attribution", label: "Attribution" },
    { value: "Attribution - Partage", label: "Attribution - Partage" },
    { value: "Attribution - partage", label: "Attribution - partage" },
    { value: "Cession", label: "Cession" },
    { value: "Cession - Attribution", label: "Cession - Attribution" },
    { value: "Cession - Echange", label: "Cession - Echange" },
    { value: "Cession - Partage", label: "Cession - Partage" },
    { value: "Cession - Transfert", label: "Cession - Transfert" },
    { value: "Compensation de créance", label: "Compensation de créance" },
    { value: "Constitution de DDP", label: "Constitution de DDP" },
    {
      value: "Constitution de Dépendance",
      label: "Constitution de Dépendance",
    },
    { value: "Contrat de mariage", label: "Contrat de mariage" },
    { value: "Création de copropriété", label: "Création de copropriété" },
    { value: "Dation", label: "Dation" },
    { value: "Donation", label: "Donation" },
    { value: "Donation - Cession", label: "Donation - Cession" },
    { value: "Donation - Partage", label: "Donation - Partage" },
    { value: "Délivrance de legs", label: "Délivrance de legs" },
    { value: "Déréliction", label: "Déréliction" },
    { value: "Expropriation", label: "Expropriation" },
    { value: "Fixation de parts", label: "Fixation de parts" },
    { value: "Fusion", label: "Fusion" },
    { value: "Gratuit", label: "Gratuit" },
    { value: "Héritage", label: "Héritage" },
    { value: "Héritage - Cession", label: "Héritage - Cession" },
    { value: "Héritage - Partage", label: "Héritage - Partage" },
    { value: "Jugement", label: "Jugement" },
    {
      value: "Liquidation de régime matrimonial",
      label: "Liquidation de régime matrimonial",
    },
    { value: "Modification", label: "Modification" },
    { value: "Modification de DDP", label: "Modification de DDP" },
    { value: "N/A", label: "N/A" },
    { value: "Partage", label: "Partage" },
    {
      value: "Partage - Fixation de Parts",
      label: "Partage - Fixation de Parts",
    },
    { value: "Prescription Acquisitive", label: "Prescription Acquisitive" },
    { value: "Rectification", label: "Rectification" },
    { value: "Remembrement foncier", label: "Remembrement foncier" },
    { value: "Rétrocession", label: "Rétrocession" },
    { value: "Révocation de donation", label: "Révocation de donation" },
    { value: "Sans soulte", label: "Sans soulte" },
    { value: "Scission", label: "Scission" },
    {
      value: "Substitution fidéicommissaire",
      label: "Substitution fidéicommissaire",
    },
    { value: "Transfert", label: "Transfert" },
    { value: "Transfert - Dotation", label: "Transfert - Dotation" },
    { value: "Transfert - Déshérence", label: "Transfert - Déshérence" },
    { value: "Transfert de Patrimoine", label: "Transfert de Patrimoine" },
    { value: "Transfert - Déshérence", label: "Transfert - Déshérence" },
    { value: "Transformation", label: "Transformation" },
    { value: "cession", label: "cession" },
    { value: "contrat de mariage", label: "contrat de mariage" },
    { value: "donation", label: "donation" },
    { value: "héritage", label: "héritage" },
    { value: "partage", label: "partage" },
  ],
};
